config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]

  # Defines the root path route ("/")
  # root "articles#index"

  resources :services, only: %i[index show new create] do
    resources :offers, only: %i[show new create]
    resources :reviews, only: %i[index new create]
  end
end

app/models/service.rb
class Service < ApplicationRecord
  include PgSearch::Model

  CATEGORIES = ["Graphic & Design", "Digital Marketing", "Writing & Translation", "Video Animation",
                "Music Audio", "Programming & Tech", "Business", "Style", "Data", "Photography"]

  belongs_to :seller, class_name: "User", foreign_key: :seller_id
  has_many :offers
  has_many :reviews
  has_one_attached :photo

  validates :title, :description, :price, :delivery_time, :category, presence: true
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 500, less_than: 100_000_000 }
  validates :delivery_time, numericality: { only_integer: true }, inclusion: { in: (1..90) }
  validates :category, inclusion: { in: CATEGORIES }

  pg_search_scope :search_by_title,
    against: [ :title ],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :user_offers

  def index
    if params[:category]
      @category = params[:category]
      @services = policy_scope(Service).where(category: @category)
    elsif params[:query]
      @query = params[:query]
      @services = policy_scope(Service).search_by_title(@query)
    else
      @services = Service.all
      @services = policy_scope(Service)
    end
  end

  def show
    @service = Service.find(params[:id])
    authorize @service
    @reviews = policy_scope(Review).where(service_id: @service)
  end

  def new
    @service = Service.new
    authorize @service
  end

  def create
    @service = Service.new(service_params)
    @service[:price] = @service[:price].to_i * 100
    @service.seller = current_user
    authorize @service

    if @service.save
      redirect_to service_path(@service), notice: "Service was successfully created"
    else
      render :new, status: :unprocessable_entity, alert: "Please fill in the required fields"
    end
  end

  private

  def service_params
    params.require(:service).permit(:title, :description, :category, :price, :delivery_time, :photo)
  end

  def user_offers
    @offers = policy_scope(Offer)
  end
end

app/views/services/_form.html.erb
<%= simple_form_for(@service) do |f| %>
  <%= f.input :title, label: 'Gig Title', placeholder: 'I will do something I am really good at' %>
  <%= f.input :description, as: :text, placeholder: 'What does the service entail?'%>
  <%= f.input :category, :as => :select, :collection => Service::CATEGORIES %>
  <%= f.input :price, label: 'Price', placeholder: '$ (SGD)' %>
  <%= f.input :delivery_time, label: 'Delivery time (days)', placeholder: 'Enter a number from 1 to 90' %>
  <%= f.input :photo, as: :file %>
  <%= f.submit 'Create Gig', class: 'btn btn-green' %>
<% end %>

app/views/services/_service-card.html.erb
<div class="service-card">
  <div class="card-profile">
    <div class="service-price d-flex justify-content-between">
      <h3><strong>Homepage or Landing Page</strong></h3>
      <h3 id="price">SGD <%= @service.price/100 %></h3>
    </div>
    <p><%= @service.description %></p>
    <p><strong><i class="fa-regular fa-clock"></i> <%= @service.delivery_time %> Days Delivery</strong></p>
    <ul class="list-unstyled">
      <li><i class="fa-solid fa-check"></i> Responsive Design</li>
      <li><i class="fa-solid fa-check"></i> Source File</li>
    </ul>
    <% unless policy(@service).edit? %>
      <%= link_to "Continue", new_service_offer_path(@service), class: "btn btn-green w-100" %>
    </div>
    <div class="mt-3 p-4 bg-secondary" style="--bs-bg-opacity: .05">
      <a href="#" class="btn btn-grey w-100">Contact Seller</a>
    </div>
  <% end %>
</div>

app/views/services/_service-details.html.erb
<div class="service-intro m-4">
  <h1 class="mb-4"><%= @service.title %></h1>
  <% if @service.photo.key%>
    <%= cl_image_tag @service.photo.key, class: "mb-4", height: 450, width: 700, crop: :fill %>
  <% else %>
    <%= image_tag('https://res.cloudinary.com/drftmp0s5/image/upload/v1678852787/development/g9j2kjmajzgz1en4j20h42h3e8w3.jpg', height: 450, width: 700) %>
  <% end %>
</div>
<div class="service-description m-4 border-bottom">
  <div class="d-flex justify-content-between align-items-center">
    <h2 class='m-0'>About This Gig </h2>
  </div>
  <p class="pt-4 pb-4"><%= @service.description %></p>
  <p><button type="button" class="btn btn-transparent-green" data-bs-toggle="modal" data-bs-target="#shareModal"><i class="fa-solid fa-share-from-square"></i> Share</button></p>
</div>
<div class="seller m-4 pt-4">
  <h2>About The Seller</h2>
  <div class="seller-tag">
    <div class="d-flex gap-3 mt-4 mb-4">
      <div class="seller-avatar">
        <% if @service.seller.photo.key %>
          <%= cl_image_tag @service.seller.photo.key, class: "avatar-large" %>
        <% else %>
          <%= image_tag('https://res.cloudinary.com/drftmp0s5/image/upload/v1678852728/development/eikdtlh3ky8vfdi8cm216xts79e9.jpg', class: "avatar-large") %>
        <% end %>
      </div>
      <div class="seller-details">
        <%= link_to @service.seller.username, user_path(@service.seller) %>
        <% unless policy(@service).edit? %>
          <a href="#" class="d-block btn btn-grey mt-3">Contact Me</a>
        <% end %>
      </div>
    </div>
    <div class="seller-details border d-flex flex-wrap justify-content-between gap-3 m-1 p-4">
      <ul class="from mt-3">
        <li>From</li>
        <li><strong><%= @service.seller.country %></strong></li>
      </ul>
      <ul class="member-since mt-3">
        <li>Member since</li>
        <li><strong>Jan 2014</strong></li>
      </ul>
      <ul class="response-time mt-3">
        <li>Avg. response time</li>
        <li><strong>2 hours</strong></li>
      </ul>
    </div>
  </div>
</div>

app/views/services/index.html.erb
<div class="container">
  <br>
  <br>
  <%= render "shared/services", services: @services %>
</div>

app/views/services/new.html.erb
<div class="p-4 border rounded w-50 mt-5 mx-auto">
  <% if current_user %>
    <%= render 'form' %>
  <% else %>
    <div class="text-center">Please sign in to view this form</div>
  <% end %>
</div>

app/views/services/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-7">
      <%= render "service-details" %>
      <%= render "shared/reviews", :locals => {reviews: @reviews} %>
    </div>
    <div class="col-1"></div>
    <div class="col-4 mt-4">
      <%= render "service-card" %>
    </div>
  </div>
  <%= render "shared/share_card" %>
</div>