config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]

  # Defines the root path route ("/")
  # root "articles#index"

  resources :services, only: %i[index show new create] do
    resources :offers, only: %i[show new create]
    resources :reviews, only: %i[index new create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
  
  has_many :services, foreign_key: 'seller_id'
  has_many :offers, foreign_key: 'buyer_id'
  has_one_attached :photo

  validates :location, presence: true

  def online?
    updated_at > 5.minutes.ago
  end

  def username
    email.split('@').first
  end

  def country
    country_name = ISO3166::Country[location]
    return location unless country_name

    country_name.translations[I18n.locale.to_s]
  end

  def self.from_omniauth(access_token)
    require 'open-uri'
    data = access_token.info
    account = User.where(email: data['email']).first
    account ||= User.new(email: data['email'], password: Devise.friendly_token[0, 20])
    account.location = "Singapore"
    image = URI.open(data['image'])
    account.photo.attach(io: image, filename: data['image'], content_type: "image/jpg")
    account.save
    account
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  before_action :set_account

  def google_oauth2
    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      # Removing extra as it can overflow some session stores
      session['devise.google_data'] = request.env['omniauth.auth'].except('extra')
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end

  private

  def set_account
    @user = User.from_omniauth(request.env['omniauth.auth'])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: :show
  before_action :user_offers

  # GET users/:id
  def show
    @user = User.find(params[:id])
    @month_created = Date::MONTHNAMES[@user.created_at.month]
    authorize @user
  end

  private

  def user_offers
    @offers = policy_scope(Offer)
  end
end

app/views/users/_card-profile.html.erb
<div class="card-profile">
  <div class='user-profile-info'>
    <div class="d-flex justify-content-between">
      <div>
        <i class="fa-solid fa-bars"></i>
        <i class="fa-solid fa-heart"></i>
      </div>
      <div class="img-wrapper">
        <% if @user.photo.key%>
          <%= cl_image_tag @user.photo.key, class: 'avatar-xl' %>
        <% else %>
          <%= image_tag('https://res.cloudinary.com/drftmp0s5/image/upload/v1678852728/development/eikdtlh3ky8vfdi8cm216xts79e9.jpg', class: 'avatar-xl') %>
        <% end %>
        <p class='text-center pt-2'><%= @user.username %></p>
      </div>
      <div>
        <% if @user.online? %>
          <p class="online">&#183 Online</p>
        <% else %>
          <p class="offline">&#183 Offline</p>
        <% end %>
      </div>
    </div>
  </div>
  <div class='btn btn-green w-100'>Contact Me</div>
  <div class="user-stats-wrapper">
    <ul class='user-stats'>
      <li><span><i class="fa-sharp fa-solid fa-location-dot"></i> From</span> <strong><%= @user.country %></strong></li>
      <li><span><i class="fa-solid fa-user"></i> Member since</span> <strong><%= @month_created %> <%= @user.created_at.year %></strong></li>
      <li><span><i class="fa-regular fa-clock"></i> Avg. Response Time</span></li>
    </ul>
  </div>
</div>

app/views/users/_service_card.html.erb
<div class="card m-4">
  <%= link_to service_path(service) do %>
    <% if service.photo.key%>
      <%= cl_image_tag service.photo.key, class: 'card-img-top' %>
    <% else %>
      <%= image_tag('https://res.cloudinary.com/drftmp0s5/image/upload/v1678852787/development/g9j2kjmajzgz1en4j20h42h3e8w3.jpg', class: 'card-img-top') %>
    <% end %>
  <% end %>
  <div class="card-content">
    <div class="card-body">
      <div class='pb-2'>
        <% if user.photo.key%>
          <%= cl_image_tag user.photo.key, class: 'avatar-xs' %>
        <% else %>
          <%= image_tag('https://res.cloudinary.com/drftmp0s5/image/upload/v1678852728/development/eikdtlh3ky8vfdi8cm216xts79e9.jpg', class: 'avatar-xs') %>
        <% end %>
        <a class="text-decoration-none text-dark" href=<%= user_path(user) %> ><%= user.username %></a>
      </div>
      <a class="text-decoration-none text-dark" href=<%= service_path(service) %>>
        <p class="card-text"><%= service.title %></p>
      </a>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <div>
          <i class="fa-solid fa-bars"></i>
          <i class="fa-solid fa-heart"></i>
        </div>
        <ul>
          <li class='text-small'>STARTING AT</li>
          <li>SGD <%= service.price/100 %></li>
        </ul>
      </li>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-4">
  <div class="row">
    <%# user info panel %>
    <div class="col-4 mr-4">
      <%= render 'card-profile' %>
    </div>
    <%# user gig panel %>
    <div class="col-8 user-gig-panel">
      <h2><%= @user.username %>'s Gigs</h2>
      <div class="row">
        <% if @user.services %>
          <% @user.services.each do |service| %>
            <div class="col-4 mb-4">
              <%= render 'service_card', service: service, user: @user %>
            </div>
          <% end %>
        <% end %>
      </div>
      <% if policy(@user).edit? %>
        <%= link_to "Create Gig", new_service_path, class: "btn btn-green w-25" %>
      <% end %>
    </div>
  </div>
</div>