config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]

  # Defines the root path route ("/")
  # root "articles#index"

  resources :services, only: %i[index show new create] do
    resources :offers, only: %i[show new create]
    resources :reviews, only: %i[index new create]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="flash flash-success alert alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="fa-sharp fa-solid fa-xmark ms-2"></i>
    </a>
  </div>
<% end %>
<% if alert %>
  <div class="flash flash-warning alert alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="fa-sharp fa-solid fa-xmark ms-2"></i>
    </a>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="bottom">
  <div class="left">
    <span><%= image_tag("FBB-logo.svg") %></span>
    <p>© Fiverr but Better International Ltd. 2023</p>
  </div>

  <div class="right">
    <ul class="socials">
      <li><a href="#" target="_blank" class="social-link"><i class="fa-brands fa-twitter"></i></a></li>
      <li><a href="#" target="_blank" class="social-link"><i class="fa-brands fa-facebook"></i></a></li>
      <li><a href="#" target="_blank" class="social-link"><i class="fa-brands fa-linkedin"></i></a></li>
      <li><a href="#" target="_blank" class="social-link"><i class="fa-brands fa-pinterest"></i></a></li>
      <li><a href="#" target="_blank" class="social-link"><i class="fa-brands fa-instagram"></i></a></li>
    </ul>

    <button class="btn btn-footer">
      <i class="fa-sharp fa-solid fa-globe"></i>
      <span>English</span>
    </button>

    <button class="btn btn-footer">
      <span>SGD</span>
    </button>

    <button class="btn btn-footer">
      <i class="fa-sharp fa-solid fa-universal-access"></i>
    </button>

  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="nav-wrapper bg-white">
  <nav class="px-4 d-flex justify-content-between navbar navbar-expand-lg bg-white">
    <a class="navbar-brand logo" href=<%= user_signed_in? ? services_path : root_path %>><%= image_tag("FBB-logo.svg") %></a>
    <%= render 'shared/search_form' %>
    <ul class="navbar-nav d-flex">
      <li class="nav-item">
        <a class="nav-link text-navy" href="#">Fiverr Business</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"><i class="fa-regular fa-bell"></i></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"><i class="fa-regular fa-envelope"></i></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"><i class="fa-regular fa-heart"></i></a>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <div class="dropdown">
            <a class="nav-link dropdown-toggle" id="dropdownMenuLink" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Orders</a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuLink">
              <% @offers.each do |offer| %>
                <li>
                  <div class="dropdown-item">
                    <div class="offer-title">
                      <a class="title text-decoration-none" href="#">
                      <div class="d-flex gap-3 align-items-center">
                        <%= cl_image_tag offer.service.photo.key, height: 80, width: 120, crop: :fill %>
                        <%= test = offer.service.title.match(/(?<=I will ).*/).to_s.capitalize%>
                      </div></a>
                    </div>
                    <div class="offer-details d-flex justify-content-between">
                      <span>Delivery Time <strong><%= offer.service.delivery_time %></strong> Days</span>
                      <span>Seller: <strong><%= offer.service.seller.username %></strong></span>
                    </div>
                  </div>
                </li>
              <% end %>
            </ul>
          </div>
        </li>
      <% end %>

      <% if current_user %>
        <li class="nav-item">
          <a class="nav-link" href="/users/<%= current_user.id %>">
            <% if current_user.photo.key%>
              <%= cl_image_tag current_user.photo.key, class: 'avatar-xs' %>
            <% else %>
              <%= image_tag('https://res.cloudinary.com/drftmp0s5/image/upload/v1678852728/development/eikdtlh3ky8vfdi8cm216xts79e9.jpg', class: 'avatar-xs') %>
            <% end %>
          </a>
        </li>
      <% end %>
      <% if user_signed_in? %>
        <%= link_to 'Logout', destroy_user_session_path, data: {turbo_method: :delete}, class: "btn btn-transparent-green" %>
      <% else %>
        <button type="button" class="btn nav-link" style="border: none; color: black" data-bs-toggle="modal" data-bs-target="#loginModal">Sign in</button>
        <button type="button" class="btn nav-link btn-transparent-green" data-bs-toggle="modal" data-bs-target="#signupModal">Join</button>
      <% end %>
    </ul>
  </nav>
</div>
<div class="nav-wrapper px-0 bg-light" >
  <div class="d-flex justify-content-evenly navbar navbar-expand-lg navbar-light mt-0 mb-0 p-0">
    <ul class="navbar-nav d-flex">
      <% Service::CATEGORIES.first(8).each do |category| %>
        <li class="nav-category mx-3 py-2">
          <%= link_to category, services_path(category: category), class: "btn-category-nav" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_review_form.html.erb
<%= simple_form_for([service, review]) do |f| %>
  <%= f.input :comment, placeholder: 'I really enjoyed...' %>
  <%= f.input :rating, collection: (1..5).to_a, input_html: {data: {controller: "star-rating"}} %>
  <%= f.submit 'Submit Review', class: 'btn btn-green' %>
<% end %>

app/views/shared/_reviews.html.erb
<h3 class="my-4">Reviews</h3>

<div>
  <div class="review_cards">
    <% @reviews.each do |review| %>
      <div class="review_card">
        <div class="d-flex gap-4">
          <div>
            <% review.rating.to_i.times do  %>
              <i class="fa-sharp fa-solid fa-star" style="color: #ffb33d;"></i>
            <% end %>
            <% (5 - review.rating.to_i).times do %>
              <i class="fa-sharp fa-regular fa-star" style="color: #ffb33d;"></i>
            <% end %>
          </div>
          <div><p style="color: #ffb33d"><%= review.rating %> | </p></div>
          <div class="text-muted"><small><p><%= time_ago_in_words(review.created_at) %> ago</p></small></div>
        </div>
        <p><%= review.comment %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_search_form.html.erb
<%= form_with url: services_path, method: :get, class: "d-flex flex-grow-1 px-4" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control bg-white py-2",
    placeholder: "What service are you looking for today?",
    required: true
  %>
  <button class='btn btn-dark'><i class="fa-solid fa-magnifying-glass"></i></button>
<% end %>

app/views/shared/_services.html.erb
<div class="services-list">
  <%= render 'shared/services_header' %>

  <%# Header for the services %>
  <div class="services-header">
    <p class="fs-6"><%= "#{services.count} #{'service'.pluralize(services.count)}" %> available</p>
  </div>

  <%# Grid for services cards %>
  <div class="row">
    <% services.each do |service| %>
      <div class="col-3 mb-4">
        <%= render 'users/service_card', service: service, user: service.seller %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_services_header.html.erb
<% if @query %>
  <h1 class="fw-bold">Results for "<%= @query %>"</h1>
<% else %>
  <h1 class="fw-bold"><%= @category.nil? ? "All Categories" : @category  %></h1>
  <p class="fs-5">This page currently shows all services available for <%= @category.nil? ? "All Categories" : @category  %></p>
<% end %>

app/views/shared/_share_card.html.erb
<div class="modal fade" id="shareModal" tabindex="-1" aria-labelledby="shareLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" style="width: 400px;">
    <div class="modal-content pb-4" style="border-radius: 8px;">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body p-0">
        <div>
          <div data-controller='clipboard' class="share-card text-center">
            <h2>Share This Gig</h2>
            <p>Spread the word about this Gig on Fiver-But-Better</p>
            <ul class="social-mediums d-flex justify-content-center">
              <li>
                <a href="https://api.whatsapp.com/send/?<%= "text=Check it out! %23FiverButBetter%3A #{@service.title} #{request.original_url}&type=custom_url&app_absent=0" %>" target="_blank"><%= image_tag("whatsapp-logo.svg") %></a>
              </li>
              <a class="twitter-share-button" href="https://twitter.com/intent/tweet?<%= "text=Check it out! %23FiverButBetter%3A #{@service.title}&url=#{request.original_url}" %>" target="_blank">
                <%= image_tag("twitter-logo.svg") %>
              </a>
              <li>
                <%= image_tag("facebook-logo.svg") %>
              </li>
              <li>
                <%= image_tag("linkedin-logo.svg", width: '54px', height: '54px', class:'pt-1 mx-1') %>
              </li>
              <li data-action='click->clipboard#copyToClipboard'>
                <svg version="1.1" id="link-icon" x="0px" y="0px"

                        viewBox="0 0 457.03 457.03"
                        xml:space="preserve">
                  <path d="M421.512,207.074l-85.795,85.767c-47.352,47.38-124.169,47.38-171.529,0c-7.46-7.439-13.296-15.821-18.421-24.465
            l39.864-39.861c1.895-1.911,4.235-3.006,6.471-4.296c2.756,9.416,7.567,18.33,14.972,25.736c23.648,23.667,62.128,23.634,85.762,0
            l85.768-85.765c23.666-23.664,23.666-62.135,0-85.781c-23.635-23.646-62.105-23.646-85.768,0l-30.499,30.532
            c-24.75-9.637-51.415-12.228-77.373-8.424l64.991-64.989c47.38-47.371,124.177-47.371,171.557,0
            C468.869,82.897,468.869,159.706,421.512,207.074z M194.708,348.104l-30.521,30.532c-23.646,23.634-62.128,23.634-85.778,0
            c-23.648-23.667-23.648-62.138,0-85.795l85.778-85.767c23.665-23.662,62.121-23.662,85.767,0
            c7.388,7.39,12.204,16.302,14.986,25.706c2.249-1.307,4.56-2.369,6.454-4.266l39.861-39.845
            c-5.092-8.678-10.958-17.03-18.421-24.477c-47.348-47.371-124.172-47.371-171.543,0L35.526,249.96
            c-47.366,47.385-47.366,124.172,0,171.553c47.371,47.356,124.177,47.356,171.547,0l65.008-65.003
            C246.109,360.336,219.437,357.723,194.708,348.104z"/>
                </svg>
              </li>
            </ul>
            <p data-clipboard-target = 'confirmation' class='d-none confirmation-message'>Copied to clipboard!</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>